### PR TITLE
C CPP template

### PR DESCRIPTION
**Pull request by ismagilli**
I have implemented C and CPP templates for this challenge.

Note for C template. I have checked all currently existing tests and have found that longest input file thru all 57 tests has length 176. Thus 1000 should be enough for the length of the array.

### CODE REVIEW

**Comment by ismagilli** [comment]
Small fix:
- Few typos was fixes in `solutions/cpp/01-ry8/explanation.md` (`app/main.c` -> `src/main.cpp` and `c` -> `cpp`)
- `codecrafers.yml` was added to C template
- Trailing empty lines was added to all files

**Comment by ismagilli** [comment]
Now I will make 2 pushes. First one is rebase. Second one is my attempt to fix failed check.

**Comment by ismagilli** [comment]
I have been mada 2 pushes. First one is rebase. Second one is my attempt to fix failed check.

**Comment by rohitpaulk** [comment]
Thank you for the PR! Will take a look this week once we've worked on adding `course-sdk add-language` support to C & C++. That'll make it easier to ensure things are consistent across all challenges (removes a lot of the rote work of copying dockerfiles etc.)

**Comment by ismagilli** [comment]
@rohitpaulk I've fixed my code but haven't push updates since I was waiting for your reply to my email. Here is the fixed code.

**Comment by ismagilli** [comment]
@rohitpaulk, have you looked my PR?

**Comment by andy1li** [comment]
@ismagilli  Thanks for the PR! We've added C and CPP support in https://github.com/codecrafters-io/build-your-own-interpreter/pull/57 and https://github.com/codecrafters-io/build-your-own-interpreter/pull/51.

**Pull request closed without merging**
